[project]
name = "downscaling-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lucas Mascena", email = "lucasmascenac@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "datetime>=6.0",
    "loguru>=0.7.3",
    "numpy>=2.5.3",
    "optuna>=5.0.0",
    "pandas>=3.0.6",
    "plotly>=7.1.0",
    "pyarrow>=25.0.1",
    "pygrib>=2.1.8",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.1",
    "torch>=2.14.0",
    "xarray>=2026.7.0",
]

[project.scripts]
downscaling-framework = "downscaling_framework:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
